---
title: "Figure 1C-D: All-Cell UMAPs with Collapsed 'IT' Subclass"
output: 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
# This sets the project root based on the repo structure.
# If you move this file, you may to set the root manually to find config.R
knitr::opts_knit$set(root.dir = dirname(dirname(rstudioapi::getSourceEditorContext()$path)))
```

```{r libraries}
library(Seurat)
library(ggplot2)
library(dplyr)
library(comparatome)
source("config.R")
```

```{r load_data}
# Load processed objects for each class
classes <- c("Glutamatergic", "GABAergic", "Nonneuronal")

objs.mouse <- list()
objs.opossum <- list()
for (cl in classes) {
  objs.mouse[[cl]] <- readRDS(paste0(dir.list$snrna$seurat$processed, "mouse_v1_", tolower(cl), "_processed.rds"))
  objs.opossum[[cl]] <- readRDS(paste0(dir.list$snrna$seurat$processed, "opossum_v1_", tolower(cl), "_processed.rds"))
}

# Merge all classes
obj.mouse <- merge(objs.mouse$Glutamatergic, y = c(objs.mouse$GABAergic, objs.mouse$Nonneuronal))
obj.opossum <- merge(objs.opossum$Glutamatergic, y = c(objs.opossum$GABAergic, objs.opossum$Nonneuronal))
```

```{r recluster}
# Re-cluster merged objects
obj.mouse <- ClusterWithSCT(obj.mouse, 1)
obj.opossum <- ClusterWithSCT(obj.opossum, 1)
```

```{r colors}
colors_list <- get_colors() # From config.R
```

```{r fig_1C, fig.width=8, fig.height=8}
# Figure 1C: Opossum all-cell UMAP with IT collapsed
obj.opossum$subclass.plot <- obj.opossum$subclass
obj.opossum$subclass.plot[obj.opossum$subclass %in% c("IT_A", "IT_B", "IT_C", "IT_D")] <- "IT"

opossum.subclass.plot.levels <- c("IT", "L5NP", "L5PT", "L6CT", "L6b",
                                   "Pvalb", "Sst", "Vip", "Lamp5", "Frem1",
                                   "Astro", "Micro", "OD", "OPC", "Endo")

Idents(obj.opossum) <- "subclass.plot"
levels(obj.opossum) <- opossum.subclass.plot.levels
colors <- as.character(colors_list[opossum.subclass.plot.levels])

p <- DimPlot(obj.opossum, reduction = "umap", label = TRUE, raster = FALSE, 
             shuffle = TRUE, cols = colors) + 
  NoLegend() + 
  xlim(-18, 18) + ylim(-18, 18) + 
  coord_equal()

print(p)
SavePNGandSVG(p, dir.list$fig1$plots, "1C_Opossum-All-Subclass-UMAP")
```

```{r fig_1D, fig.width=8, fig.height=8}
# Figure 1D: Mouse all-cell UMAP with IT collapsed
obj.mouse$subclass.plot <- obj.mouse$subclass
obj.mouse$subclass.plot[obj.mouse$subclass %in% c("L2/3", "L4", "L5IT", "L6IT")] <- "IT"

mouse.subclass.plot.levels <- c("IT", "L5NP", "L5PT", "L6CT", "L6b", 
                                "Pvalb", "Sst", "Vip", "Lamp5", "Frem1", "Stac",
                                "Astro", "Micro", "OD", "OPC", "Endo", "VLMC")

Idents(obj.mouse) <- "subclass.plot"
levels(obj.mouse) <- mouse.subclass.plot.levels
colors <- as.character(colors_list[mouse.subclass.plot.levels])

p <- DimPlot(obj.mouse, reduction = "umap", label = TRUE, raster = FALSE, 
             shuffle = TRUE, cols = colors) + 
  NoLegend() + 
  xlim(-16, 16) + ylim(-17, 15) + 
  coord_equal()

print(p)
SavePNGandSVG(p, dir.list$fig1$plots, "1D_Mouse-All-Subclass-UMAP")
```
